// 问题记录
export const mockIssues = [
  {
    id: "issue-1",
    type: "issue",
    title: "主体结构梁柱连接处钢筋绑扎不符合规范",
    date: "2023-05-15",
    location: "3号楼4层东侧",
    status: "pending",
    icon: () => null,
    description: "在检查过程中发现3号楼4层东侧的梁柱连接处钢筋绑扎不符合规范要求，存在搭接长度不足、绑扎不牢固等问题。",
    responsibleUnit: "某建筑公司",
    dueDate: "2023-05-20",
    tags: ["结构", "钢筋", "重要"],
  },
  {
    id: "issue-2",
    type: "issue",
    title: "外墙保温材料厚度不足",
    date: "2023-05-16",
    location: "2号楼西立面",
    status: "resolved",
    icon: () => null,
    description: "经测量，2号楼西立面外墙保温材料厚度为45mm，低于设计要求的50mm。",
    responsibleUnit: "某装饰公司",
    dueDate: "2023-05-25",
    tags: ["外墙", "保温", "材料"],
  },
  {
    id: "issue-3",
    type: "issue",
    title: "电气管线敷设间距不符合规范",
    date: "2023-05-17",
    location: "1号楼配电室",
    status: "pending",
    icon: () => null,
    description: "1号楼配电室内强弱电管线间距不足，不符合规范要求，存在安全隐患。",
    responsibleUnit: "某电气公司",
    dueDate: "2023-05-22",
    tags: ["电气", "安全", "重要"],
  },
]

import type { SupervisionRecord } from "./api-service"

export const mockSupervisionRecords: SupervisionRecord[] = [
  {
    id: 1,
    project_name: "天安门城楼修缮工程（测试用）",
    construction_unit: "中建八局（故宫特战队）",
    pangzhan_unit: "",
    supervision_company: "紫禁城监理有限公司",
    start_datetime: null,
    end_datetime: null,
    work_overview: "符合《古建筑修缮施工规范》GB/T 50165-2025要求",
    pre_work_check_content: "正常，琉璃瓦搬运使用特制防震推车，为金水桥临时搭建防尘罩",
    supervising_personnel: "张爱国, 王红旗",
    issues_and_opinions:
      "正脊第3块琉璃瓦出现0.5mm裂缝，要求使用故宫库存同批次瓦件更换；毛主席像框有3处金漆氧化，安排故宫文物修复专家现场处理",
    rectification_status: "琉璃瓦更换：已完成（附文物局批文编号GW20251001-003）；金漆修复：进行中（预计3天完工）",
    remarks:
      "本记录纯属虚构，致敬天安门守护者（狗头保命）；为配合国庆庆典暂停施工2小时；天气：晴空万里，22℃；签名：未获取（因项目经理去参加升旗仪式），未获取（监理被临时抽调检查观礼台）",
    construction_enterprise: "中建八局（故宫特战队）",
    supervising_enterprise: "紫禁城监理有限公司",
    supervising_organization: null,
    on_site_supervising_personnel: "张爱国, 王红旗",
    document_urls: null,
    created_at: "2025-05-22T10:25:39",
    updated_at: "2025-05-22T10:25:39",
  },
  {
    id: 2,
    project_name: "故宫博物院文物保护修复工程",
    construction_unit: "北京古建筑修缮有限公司",
    pangzhan_unit: "故宫博物院工程部",
    supervision_company: "北京文物保护监理公司",
    start_datetime: "2025-05-23T08:00:00",
    end_datetime: "2025-05-23T17:00:00",
    work_overview: "太和殿屋顶琉璃瓦更换及木结构加固",
    pre_work_check_content: "检查施工材料质量，确认古建筑保护措施到位",
    supervising_personnel: "李文华, 赵建国",
    issues_and_opinions: "发现部分木梁有轻微虫蛀，建议进行防虫处理",
    rectification_status: "已安排专业防虫处理，预计明日完成",
    remarks: "严格按照文物保护要求施工",
    construction_enterprise: "北京古建筑修缮有限公司",
    supervising_enterprise: "北京文物保护监理公司",
    supervising_organization: "故宫博物院监理部",
    on_site_supervising_personnel: "李文华, 赵建国",
    document_urls: "https://example.com/doc1.pdf,https://example.com/doc2.pdf",
    created_at: "2025-05-23T08:30:00",
    updated_at: "2025-05-23T08:30:00",
  },
  {
    id: 3,
    project_name: "颐和园古建筑群修缮项目",
    construction_unit: "中国古建筑工程有限公司",
    pangzhan_unit: "颐和园管理处",
    supervision_company: "北京园林监理公司",
    start_datetime: "2025-05-22T09:00:00",
    end_datetime: "2025-05-22T16:30:00",
    work_overview: "佛香阁彩画修复及结构加固",
    pre_work_check_content: "材料检验合格，施工人员资质齐全",
    supervising_personnel: "王美丽, 张强",
    issues_and_opinions: "彩画颜料调配需要严格按照传统工艺",
    rectification_status: "已邀请故宫专家现场指导，按传统工艺执行",
    remarks: "天气良好，施工进展顺利",
    construction_enterprise: "中国古建筑工程有限公司",
    supervising_enterprise: "北京园林监理公司",
    supervising_organization: "颐和园工程监理部",
    on_site_supervising_personnel: "王美丽, 张强",
    document_urls: null,
    created_at: "2025-05-22T16:45:00",
    updated_at: "2025-05-22T16:45:00",
  },
]

// 监理日志
export const mockDailyLogs = [
  {
    id: "log-1",
    type: "daily-log",
    title: "2023年5月15日监理日志",
    date: "2023-05-15",
    location: "整个工地",
    status: "completed",
    icon: () => null,
    description:
      "今日天气晴朗，气温22-28℃，现场施工人员约120人。主要施工内容：3号楼主体结构施工、1号楼外墙保温施工、2号楼室内管线敷设。",
    tags: ["天气", "人员", "进度"],
  },
  {
    id: "log-2",
    type: "daily-log",
    title: "2023年5月16日监理日志",
    date: "2023-05-16",
    location: "整个工地",
    status: "completed",
    icon: () => null,
    description:
      "今日天气多云，气温20-25℃，现场施工人员约115人。主要施工内容：地下室防水施工、3号楼主体结构施工、2号楼外墙砌筑。",
    tags: ["天气", "人员", "进度"],
  },
]

// 会议纪要
export const mockMeetingMinutes = [
  {
    id: "meeting-1",
    type: "meeting",
    title: "工程例行协调会议纪要",
    date: "2023-05-14",
    time: "14:30-16:00",
    location: "项目部会议室",
    attendees: 12,
    status: "completed",
    icon: () => null,
    description: "讨论了工程进度、质量控制、安全管理等问题，明确了下阶段工作重点和各方职责。",
    tags: ["协调会", "进度", "质量"],
  },
  {
    id: "meeting-2",
    type: "meeting",
    title: "外墙保温施工技术交底会",
    date: "2023-05-16",
    time: "09:00-10:30",
    location: "项目部会议室",
    attendees: 8,
    status: "completed",
    icon: () => null,
    description: "对外墙保温施工工艺、材料要求、质量控制点等进行了详细交底，明确了施工标准和验收要求。",
    tags: ["技术交底", "外墙", "保温"],
  },
]
